version: '3.3'

services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "3001:3001"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/opt/app:delegated
      #- notused:/opt/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - WAIT_HOSTS:mongo:27017

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      # - /opt/app/data/db/mongo001:/opt/data/mongodb
      - ./data:/opt/data/mongodb
    ports:
      - "27017:27017"
volumes:
  mongo_data:

